worker_processes auto;

pid /home/container/conf/nginx/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    access_log /dev/stdout;
    error_log /dev/stderr;

    client_body_temp_path /home/container/conf/nginx/client_body;
    proxy_temp_path /home/container/conf/nginx/proxy;
    fastcgi_temp_path /home/container/conf/nginx/fastcgi;
    uwsgi_temp_path /home/container/conf/nginx/uwsgi;
    scgi_temp_path /home/container/conf/nginx/scgi;

    include /home/container/conf/nginx/server.conf;
}
