server {
    listen __SERVER_PORT__;

    root /home/container/wordpress;
    index index.php index.html;

    access_log /dev/stdout;
    error_log /dev/stderr;

    client_max_body_size 128M;

    location / {
        try_files $uri $uri/ /index.php?$args;
    }

    location ~ \.php$ {
        try_files $uri =404;

        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;

        include fastcgi_params;
        # Preserve the original Host header including a non-standard port.
	# Required for WordPress Multisite when running behind Pelican allocations.
	fastcgi_param HTTP_HOST $http_host;
	fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|webp|svg)$ {
        expires 24h;
        log_not_found off;
    }

    location ^~ /blogs.dir {
        internal;
        alias /home/container/wordpress/wp-content/blogs.dir;
        access_log off;
        log_not_found off;
        expires max;
    }

    if (!-e $request_filename) {
        rewrite /wp-admin$ $scheme://$host$uri/ permanent;
        rewrite ^/[_0-9a-zA-Z-]+(/wp-.*) $1 last;
        rewrite ^/[_0-9a-zA-Z-]+(/.*\.php)$ $1 last;
    }
}
